/**
 * HAWT! E-Commerce — Product Seeder
 *
 * 50 products sourced directly from the local DB export.
 * All image_url values point to local /images/products/ files.
 * All flags (is_new_in, is_on_sale, is_clearance, discount_percentage)
 * are set explicitly — no derivation logic.
 *
 * Usage:
 *   npm run db:seed
 *
 * WARNING: Truncates products + product_variants (cascades to cart_items /
 *          order_items). Do NOT run against production without intent.
 */

require('dotenv').config();
const { Pool } = require('pg');

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized: false } : false,
});

function slugify(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function randInt(min, max) { return Math.floor(Math.random() * (max - min + 1)) + min; }

const CATEGORY_SKU = {
  'Accessories': 'AC',
  'Bottoms':     'BT',
  'Co-ords':     'CO',
  'Dresses':     'DR',
  'Shirts':      'SH',
};

// ─── 50 PRODUCTS — exact data from local DB ───────────────────────────────────

const PRODUCTS = [

  // ── ACCESSORIES (9) ─────────────────────────────────────────────────────────
  {
    name:                'Black Messenger Shoulder Bag',
    description:         'Structured black messenger bag with front zip pocket and padded strap. Built for all-day carry.',
    sub:                 'structured everyday carry',
    category:            'Accessories',
    base_price:          1799,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/acc-2.png',
    tags:                [],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Black Sling Crossbody Bag',
    description:         'Sleek black sling bag with multi-zip compartments and adjustable strap. Fits your essentials hands-free.',
    sub:                 'multi-zip streetwear sling',
    category:            'Accessories',
    base_price:          1499,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/acc-1.png',
    tags:                [],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Black Weekend Duffle Bag',
    description:         'Large black duffle with leather-trim handles and detachable shoulder strap. Your ultimate weekend companion.',
    sub:                 'premium overnight travel bag',
    category:            'Accessories',
    base_price:          3499,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/acc-3.png',
    tags:                [],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'HAWT! Silver Keychain',
    description:         'Heavy-gauge silver HAWT! logo keychain. Rep the brand wherever you go.',
    sub:                 'branded metal logo keyring',
    category:            'Accessories',
    base_price:          399,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/acc-6.png',
    tags:                [],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Mirrored Wraparound Sunglasses',
    description:         'Futuristic wraparound shield sunglasses with silver mirrored lenses. UV400 protection. Statement eyewear.',
    sub:                 'futuristic shield-frame silver sunnies',
    category:            'Accessories',
    base_price:          1299,
    sale_price:          1000.23,
    badge:               'Sale',
    image_url:           '/images/products/acc-9.png',
    tags:                [],
    is_new_in:           false,
    is_on_sale:          true,
    is_clearance:        false,
    discount_percentage: 23,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Molten Silver Chunky Earrings',
    description:         'Chunky silver stud earrings with an organic molten finish. Textured, bold, and effortlessly cool.',
    sub:                 'sculptural irregular stud earrings',
    category:            'Accessories',
    base_price:          699,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/acc-7.png',
    tags:                [],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Silver Arc Pendant Necklace',
    description:         'Sculptural curved silver pendant on a sleek snake chain. Effortless and elegant.',
    sub:                 'fluid curved pendant on snake chain',
    category:            'Accessories',
    base_price:          899,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/acc-5.png',
    tags:                [],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Silver Liquid Open Ring',
    description:         'Open-band silver ring with a fluid, liquid-form finish. Adjustable and stackable.',
    sub:                 'adjustable molten-form open band',
    category:            'Accessories',
    base_price:          599,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/acc-8.png',
    tags:                [],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Silver Tag Pendant Necklace',
    description:         'Minimalist silver rectangular tag pendant on a fine curb chain. A clean everyday staple.',
    sub:                 'rectangular silver pendant on curb chain',
    category:            'Accessories',
    base_price:          799,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/acc-4.png',
    tags:                [],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },

  // ── BOTTOMS (8) ─────────────────────────────────────────────────────────────
  {
    name:                'Beige Pleated Wide-Leg Trousers',
    description:         'Double front pleats and a high waist in a warm sand beige. Fluid fabric drapes beautifully — office to evening without a change.',
    sub:                 'Sand beige tailored wide-leg trousers',
    category:            'Bottoms',
    base_price:          2499,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/bottom-2.png',
    tags:                ['trousers', 'pleated', 'beige', 'women', 'tailored'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Chocolate Cargo Wide-Leg Pants',
    description:         'Washed chocolate brown cargo pants in a relaxed wide-leg fit. Deep side pockets and elasticated waist for all-day ease.',
    sub:                 'Chocolate brown utility cargo pants',
    category:            'Bottoms',
    base_price:          2299,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/bottom-6.png',
    tags:                ['cargo', 'wide-leg', 'brown', 'men'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Grey Pinstripe Pleated Trousers',
    description:         'Double-pleated front with a wide-leg break. Ivory ground with fine grey pinstripes — a modern take on the classic tailored trouser.',
    sub:                 'Ivory & grey pinstripe wide-leg pleated pants',
    category:            'Bottoms',
    base_price:          2799,
    sale_price:          2099,
    badge:               'Sale',
    image_url:           '/images/products/bottom-5.png',
    tags:                ['pinstripe', 'pleated', 'grey', 'men', 'tailored'],
    is_new_in:           false,
    is_on_sale:          true,
    is_clearance:        false,
    discount_percentage: 25,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Ivory Pinstripe Drawstring Trousers',
    description:         'Classic black-on-ivory pinstripe in a fluid wide-leg cut with drawstring waist — dressier than joggers, more relaxed than tailoring.',
    sub:                 'Ivory & black pinstripe relaxed trousers',
    category:            'Bottoms',
    base_price:          2599,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/bottom-4.png',
    tags:                ['pinstripe', 'drawstring', 'ivory', 'men'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Khaki Washed Jogger Pants',
    description:         'Garment-washed for a soft, broken-in feel. Elastic waist, tapered leg and ribbed cuffed hem in a warm khaki tone.',
    sub:                 'Khaki garment-washed joggers with cuffed hem',
    category:            'Bottoms',
    base_price:          1799,
    sale_price:          1299,
    badge:               'Sale',
    image_url:           '/images/products/bottom-8.png',
    tags:                ['joggers', 'khaki', 'washed', 'men'],
    is_new_in:           false,
    is_on_sale:          true,
    is_clearance:        false,
    discount_percentage: 28,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Olive Wide-Leg Cargo Pants',
    description:         'Relaxed wide-leg silhouette with side cargo pockets in olive green cotton twill. Equal parts utility and style.',
    sub:                 'Olive green utility cargo trousers',
    category:            'Bottoms',
    base_price:          2199,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/bottom-1.png',
    tags:                ['cargo', 'wide-leg', 'olive', 'women'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Striped Linen Drawstring Pants',
    description:         'Blue, white and ecru vertical stripes in a relaxed wide-leg linen cut with elasticated drawstring waist. Summer in pant form.',
    sub:                 'Blue & white stripe wide-leg linen trousers',
    category:            'Bottoms',
    base_price:          2299,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/bottom-3.png',
    tags:                ['linen', 'stripe', 'drawstring', 'men', 'wide-leg'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Wide-Leg Boyfriend Jeans',
    description:         'Low-rise with a voluminous wide-leg silhouette in light blue washed denim. Worn-in creases and a relaxed waist — the new denim essential.',
    sub:                 'Light blue washed wide-leg jeans',
    category:            'Bottoms',
    base_price:          2999,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/bottom-7.png',
    tags:                ['jeans', 'wide-leg', 'denim', 'women'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },

  // ── CO-ORDS (9) ─────────────────────────────────────────────────────────────
  {
    name:                'Abstract Brushstroke Shirt & Shorts',
    description:         'Navy and olive abstract brushstrokes on ivory. The short-sleeve shirt and matching shorts are the only outfit you need poolside.',
    sub:                 'Ivory & navy brushstroke print resort set',
    category:            'Co-ords',
    base_price:          3499,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/coord-9.png',
    tags:                ['co-ord', 'resort', 'brushstroke', 'men', 'shorts'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Beige Stripe Shirt & Wide-Leg Co-ord',
    description:         'Tonal beige and cream vertical stripes on a matching crop button shirt and wide-leg pants. Linen-blend for all-day breathability.',
    sub:                 'Vertical-stripe crop shirt & pants set',
    category:            'Co-ords',
    base_price:          3499,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/coord-1.png',
    tags:                ['co-ord', 'stripe', 'linen', 'women'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Blue Tropical Toile Co-ord',
    description:         'Classic toile-de-jouy reimagined in tropical motifs — palm trees and botanicals in navy blue on ivory. A statement set with resort energy.',
    sub:                 'Ivory & blue tropical print shirt & pants set',
    category:            'Co-ords',
    base_price:          3999,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/coord-3.png',
    tags:                ['co-ord', 'toile', 'tropical', 'women'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Blush Satin Pyjama Co-ord',
    description:         'Blush pink satin with contrasting black piping on the collar and cuffs — elevated pyjama dressing for day-to-night transitions.',
    sub:                 'Pink satin button shirt & wide-leg pants',
    category:            'Co-ords',
    base_price:          3299,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/coord-6.png',
    tags:                ['co-ord', 'satin', 'pink', 'women', 'pyjama-style'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Dark Green Geometric Co-ord',
    description:         'Bold abstract shapes in forest green and ivory on a luxe crepe fabric. The wide silhouette belt-tie waist adds definition to the relaxed cut.',
    sub:                 'Abstract dark green & ivory print set',
    category:            'Co-ords',
    base_price:          4299,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/coord-5.png',
    tags:                ['co-ord', 'geometric', 'green', 'women'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Ivory Floral Shirt & Pants Set',
    description:         'Soft pink and green florals on ivory — the matching shirt and wide-leg pants look effortlessly put together with minimal effort.',
    sub:                 'Blush floral wide-leg co-ord',
    category:            'Co-ords',
    base_price:          3799,
    sale_price:          3001.21,
    badge:               'Sale',
    image_url:           '/images/products/coord-4.png',
    tags:                ['co-ord', 'floral', 'ivory', 'women'],
    is_new_in:           false,
    is_on_sale:          true,
    is_clearance:        false,
    discount_percentage: 21,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Olive Linen Polo & Shorts Co-ord',
    description:         'Matching olive green linen-blend camp polo and drawstring shorts. The go-to summer set for men who hate overthinking outfits.',
    sub:                 'Olive green linen polo & shorts set for men',
    category:            'Co-ords',
    base_price:          3199,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/coord-7.png',
    tags:                ['co-ord', 'linen', 'olive', 'men', 'shorts'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Sage Floral Crop Shirt Co-ord',
    description:         'Delicate cream florals scattered across sage green. The crop button shirt and matching wide-leg pants create a relaxed, polished look.',
    sub:                 'Sage green floral shirt & wide-leg pants',
    category:            'Co-ords',
    base_price:          3799,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/coord-2.png',
    tags:                ['co-ord', 'floral', 'sage', 'women'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Sage Tee & Cream Shorts Co-ord',
    description:         'Tonal two-piece in relaxed cotton — sage green logo tee paired with cream drawstring shorts. Minimal, clean, done.',
    sub:                 'Sage green tee & cream drawstring shorts',
    category:            'Co-ords',
    base_price:          2799,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/coord-8.png',
    tags:                ['co-ord', 'casual', 'tee', 'men', 'shorts'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },

  // ── DRESSES (7) ─────────────────────────────────────────────────────────────
  {
    name:                'Chocolate Bodycon Maxi Dress',
    description:         'A sleek bodycon silhouette in rich chocolate brown with thin spaghetti straps. Matte jersey that sculpts without constricting.',
    sub:                 'Chocolate brown spaghetti-strap maxi',
    category:            'Dresses',
    base_price:          2999,
    sale_price:          2299,
    badge:               'Sale',
    image_url:           '/images/products/dress-5.png',
    tags:                ['maxi', 'bodycon', 'brown', 'women'],
    is_new_in:           false,
    is_on_sale:          true,
    is_clearance:        false,
    discount_percentage: 23,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Ivory Belted Sleeveless Jumpsuit',
    description:         'Sleeveless wide-leg jumpsuit with notched lapels and a waist-defining self-belt in ivory crepe. Effortlessly polished.',
    sub:                 'Cream lapel wide-leg belted jumpsuit',
    category:            'Dresses',
    base_price:          3799,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/dress-3.png',
    tags:                ['jumpsuit', 'ivory', 'belted', 'sleeveless', 'women'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Ivory Collared Button-Down Mini',
    description:         'Sleeveless shirt-dress silhouette with a pointed collar and full button placket. Clean ivory with a structured shape that always looks intentional.',
    sub:                 'Ivory sleeveless shirt-dress mini',
    category:            'Dresses',
    base_price:          2499,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/dress-7.png',
    tags:                ['mini', 'shirt-dress', 'ivory', 'women', 'sleeveless'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Ivory Floral Cutout Maxi Dress',
    description:         'Romantic blue florals on ivory with a subtle waist cutout detail. Floor-length with a flowing skirt — the dress you\'ll wear all summer.',
    sub:                 'Ivory maxi with blue floral print & waist cutout',
    category:            'Dresses',
    base_price:          3499,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/dress-6.png',
    tags:                ['maxi', 'floral', 'cutout', 'ivory', 'women'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Ivory Spaghetti Strap Midi Dress',
    description:         'Delicate spaghetti straps and a flowing A-line silhouette in ivory. The dress that works for every occasion you can\'t decide what to wear to.',
    sub:                 'Ivory A-line midi slip dress',
    category:            'Dresses',
    base_price:          2799,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/dress-4.png',
    tags:                ['midi', 'slip', 'ivory', 'women', 'strappy'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Light Wash Denim Dungarees',
    description:         'Relaxed wide-leg dungarees in light-wash denim. Adjustable straps and side pockets — functional, casual and endlessly wearable.',
    sub:                 'Wide-leg light wash denim overalls',
    category:            'Dresses',
    base_price:          3499,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/dress-2.png',
    tags:                ['dungarees', 'denim', 'overalls', 'women'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Navy Belted Collared Jumpsuit',
    description:         'Structured short-sleeve jumpsuit with a collared neckline and self-belt at the waist. Navy blue cotton-blend that keeps its shape all day.',
    sub:                 'Navy short-sleeve belted wide-leg jumpsuit',
    category:            'Dresses',
    base_price:          3299,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/dress-1.png',
    tags:                ['jumpsuit', 'navy', 'belted', 'unisex'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },

  // ── SHIRTS (17) ─────────────────────────────────────────────────────────────
  {
    name:                '"Escape the Ordinary" Slogan Shirt',
    description:         '"Escape The Ordinary" — bold lettering layered over abstract charcoal brushwork. For those who dress with intention.',
    sub:                 'Ivory & black brushstroke slogan shirt',
    category:            'Shirts',
    base_price:          2499,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/top-14.png',
    tags:                ['resort', 'slogan', 'typography', 'men'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                '"Escape" Mountain Print Shirt',
    description:         'Mountains, a globe and "Wander. Explore. Discover." printed in editorial typography. The wanderer\'s uniform.',
    sub:                 'Ivory resort shirt with mountain & globe motifs',
    category:            'Shirts',
    base_price:          2599,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/top-15.png',
    tags:                ['resort', 'travel', 'mountain', 'men'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                '"Journey Shapes You" Slogan Shirt',
    description:         'Typography meets art: "The Journey Shapes You" printed alongside ink-wash brushstrokes. Wear your philosophy.',
    sub:                 'Ivory & black slogan resort shirt',
    category:            'Shirts',
    base_price:          2499,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/top-13.png',
    tags:                ['resort', 'slogan', 'typography', 'men'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Abstract Ink Brush Resort Shirt',
    description:         'Hand-painted ink brush strokes printed on lightweight viscose. Open camp collar and chest pocket — perfect from beach bar to rooftop.',
    sub:                 'Ivory & grey brushstroke short-sleeve',
    category:            'Shirts',
    base_price:          2199,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/top-8.png',
    tags:                ['resort', 'print', 'camp-collar', 'men'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Colorblock Raglan Oversized Tee',
    description:         'White, grey and black colorblock panels on a relaxed raglan silhouette. Crafted in heavyweight 240 GSM cotton — structured enough to wear alone, soft enough to live in.',
    sub:                 'Easy-fit unisex drop-shoulder tee',
    category:            'Shirts',
    base_price:          1299,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/top-1.png',
    tags:                ['oversized', 'tee', 'unisex', 'colorblock'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Contrast Stitch Long-Sleeve Crop',
    description:         'Exposed contrast topstitching frames the square neckline and cuffs in a subtle utilitarian detail. Ribbed jersey for a second-skin fit.',
    sub:                 'Dark brown square-neck long-sleeve',
    category:            'Shirts',
    base_price:          1199,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/top-4.png',
    tags:                ['crop', 'long-sleeve', 'ribbed', 'women'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Geometric Block Print Resort Shirt',
    description:         'Strong black geometric shapes contrast against an off-white ground. Soft viscose drape and a relaxed fit that works tucked or untucked.',
    sub:                 'Cream & black bold geometric print',
    category:            'Shirts',
    base_price:          2199,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/top-9.png',
    tags:                ['resort', 'geometric', 'camp-collar', 'men'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Green Splatter Resort Shirt',
    description:         'Grunge-meets-resort: forest green ink splatter across a crisp off-white base. Lightweight and breezy for long summer days.',
    sub:                 'Ivory & forest green paint-splatter print',
    category:            'Shirts',
    base_price:          2299,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/top-10.png',
    tags:                ['resort', 'splatter', 'green', 'men'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Off-Shoulder Ruched Crop Top',
    description:         'A cinched twist-front detail draws the off-shoulder neckline into a flattering ruched gather. Stretch jersey fabric moves with you all day.',
    sub:                 'Chocolate brown bardot crop',
    category:            'Shirts',
    base_price:          999,
    sale_price:          799,
    badge:               'Sale',
    image_url:           '/images/products/top-2.png',
    tags:                ['crop', 'off-shoulder', 'ruched', 'women'],
    is_new_in:           false,
    is_on_sale:          true,
    is_clearance:        false,
    discount_percentage: 20,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'One-Shoulder Cutout Crop Top',
    description:         'One shoulder, one cutout, infinite outfit possibilities. The asymmetric construction sits close to the body without clinging.',
    sub:                 'Taupe asymmetric cutout top',
    category:            'Shirts',
    base_price:          1099,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/top-3.png',
    tags:                ['crop', 'cutout', 'asymmetric', 'women'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Salt Water Heals Palm Shirt',
    description:         '"Salt water heals everything" — embroidered-style palm trees and waves on the softest blush pink. The beach called, it wants this shirt back.',
    sub:                 'Blush pink palm print women\'s resort shirt',
    category:            'Shirts',
    base_price:          1999,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/top-17.png',
    tags:                ['resort', 'pink', 'palm', 'women'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Soft Days Tropical Resort Shirt',
    description:         '"Soft days. Wild heart. Clear mind." printed over ocean waves and palm trees. Linen-blend, oversized fit for effortless coastal dressing.',
    sub:                 'Cream palm & wave print women\'s resort shirt',
    category:            'Shirts',
    base_price:          1999,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/top-16.png',
    tags:                ['resort', 'tropical', 'slogan', 'women'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['XS', 'S', 'M', 'L', 'XL'],
  },
  {
    name:                'Tropical Eye Print Resort Shirt',
    description:         'A surrealist blend of palm trees, eyes and sun symbols printed over an ivory base. Statement resort wear that travels well.',
    sub:                 'Ivory resort shirt with palm & eye motifs',
    category:            'Shirts',
    base_price:          2399,
    sale_price:          null,
    badge:               'New In',
    image_url:           '/images/products/top-12.png',
    tags:                ['resort', 'tropical', 'surrealist', 'men'],
    is_new_in:           true,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Waffle Knit Henley Long-Sleeve',
    description:         'Classic henley button placket meets waffle-knit texture in a relaxed fit. Raglan sleeves and contrast stitching keep it modern.',
    sub:                 'Black textured henley for men',
    category:            'Shirts',
    base_price:          1499,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/top-5.png',
    tags:                ['henley', 'waffle-knit', 'long-sleeve', 'men'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Washed Muscle Sleeveless Tee',
    description:         'Wide-cut armholes and a relaxed boxy body in garment-washed cotton. No logo, no fuss — just a perfect layering piece or standalone summer essential.',
    sub:                 'Charcoal drop-armhole tank',
    category:            'Shirts',
    base_price:          899,
    sale_price:          699,
    badge:               'Sale',
    image_url:           '/images/products/top-7.png',
    tags:                ['tank', 'muscle', 'sleeveless', 'men', 'washed'],
    is_new_in:           false,
    is_on_sale:          true,
    is_clearance:        false,
    discount_percentage: 22,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Washed Oversized Polo',
    description:         'Garment-washed for an intentionally faded, worn-in look. The open resort collar and dropped shoulders make this the easiest top to reach for.',
    sub:                 'Charcoal acid-wash open collar polo',
    category:            'Shirts',
    base_price:          1399,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/top-6.png',
    tags:                ['polo', 'washed', 'oversized', 'men'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
  {
    name:                'Whirlpool Abstract Resort Shirt',
    description:         'Hypnotic concentric rings and dot patterns printed in rich black on ecru. The kind of shirt that starts conversations.',
    sub:                 'Ivory & black swirl print short-sleeve',
    category:            'Shirts',
    base_price:          2299,
    sale_price:          null,
    badge:               null,
    image_url:           '/images/products/top-11.png',
    tags:                ['resort', 'abstract', 'whirlpool', 'men'],
    is_new_in:           false,
    is_on_sale:          false,
    is_clearance:        false,
    discount_percentage: 0,
    sizes:               ['S', 'M', 'L', 'XL', 'XXL'],
  },
];

// ─── SEED ─────────────────────────────────────────────────────────────────────

async function seed() {
  const client = await pool.connect();

  try {
    await client.query('BEGIN');

    console.log('⚡  Truncating product_variants + products …');
    await client.query('TRUNCATE product_variants, products RESTART IDENTITY CASCADE');

    const allVariants = [];
    const catCounters = {};

    for (let i = 0; i < PRODUCTS.length; i++) {
      const p    = PRODUCTS[i];
      const code = CATEGORY_SKU[p.category];

      if (!code) {
        console.warn(`  [SKIP] Unknown category: "${p.category}"`);
        continue;
      }

      catCounters[p.category] = (catCounters[p.category] || 0) + 1;
      const catIdx = catCounters[p.category];
      const slug   = `${slugify(p.name)}-${code.toLowerCase()}-${String(catIdx).padStart(3, '0')}`;
      const skuPfx = `HWT-${code}-${String(i + 1).padStart(3, '0')}`;

      const { rows } = await client.query(
        `INSERT INTO products
           (name, slug, description, category, sku_prefix,
            base_price, sale_price, image_url, alt_image_url,
            badge, sub, tags,
            is_new_in, is_on_sale, is_clearance, discount_percentage)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16)
         RETURNING id`,
        [
          p.name,
          slug,
          p.description,
          p.category,
          skuPfx,
          p.base_price.toFixed(2),
          p.sale_price != null ? p.sale_price.toFixed(2) : null,
          p.image_url,
          null,
          p.badge               || null,
          p.sub                 || null,
          p.tags                || [],
          p.is_new_in,
          p.is_on_sale,
          p.is_clearance,
          p.discount_percentage,
        ]
      );

      const productId = rows[0].id;

      for (const size of p.sizes) {
        allVariants.push({
          product_id:   productId,
          size,
          sku:          `${skuPfx}-${size.replace(/\s+/g, '')}`,
          stock_qty:    randInt(12, 60),
          reserved_qty: 0,
        });
      }

      console.log(`  [${code}] ${p.name}`);
    }

    // Batch-insert variants
    console.log(`\n  Inserting ${allVariants.length} variants …`);

    const placeholders = [];
    const params       = [];
    let   n            = 1;

    for (const v of allVariants) {
      placeholders.push(`($${n},$${n+1},$${n+2},$${n+3},$${n+4})`);
      params.push(v.product_id, v.size, v.sku, v.stock_qty, v.reserved_qty);
      n += 5;
    }

    await client.query(
      `INSERT INTO product_variants (product_id, size, sku, stock_qty, reserved_qty)
       VALUES ${placeholders.join(',')}`,
      params
    );

    await client.query('COMMIT');

    const catSummary = Object.entries(catCounters)
      .map(([name, count]) => `${name}(${count})`)
      .join(' · ');

    console.log('');
    console.log('✅  Seed complete.');
    console.log(`    Products : ${PRODUCTS.length}`);
    console.log(`    Variants : ${allVariants.length}`);
    console.log(`    ${catSummary}`);
    console.log('');

  } catch (err) {
    await client.query('ROLLBACK');
    console.error('❌  Seed failed — rolled back.\n', err);
    process.exitCode = 1;
  } finally {
    client.release();
    await pool.end();
  }
}

seed();
